# Generated by Django 5.1.4 on 2025-01-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('age', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('size', models.DecimalField(decimal_places=1, max_digits=500, null=True)),
                ('description', models.TextField()),
                ('age_limited', models.BooleanField()),
                ('buyer_1', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('buyer_2', models.BooleanField()),
                ('buyer', models.ManyToManyField(to='task1.buyer')),
            ],
        ),
    ]
